# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c50bf6ef0698a8db55f7b0d4cb46bb3d90c2bab60ef6babaa20d664101bd0320f0e27926ae609634431dd07fe8c69bd3161bf2aaedb27ff1ca6cd44320da2bdd

test:
  secret_key_base: 6b5a683918d3b110c20e284854aff4c725c253ddec9d9259a17ecadceab71149ef7bbdbe340393c567f42f934d615ba833c0a56b08eeaab3e5d284d0ee2babbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
